### PR TITLE
Add compatibility with rails 7+

### LINKED ISSUE #21: Rails 7 deprecated use of sum
On Rails 7 I'm getting deprecation errors:

```
DEPRECATION WARNING: Rails 7.0 has deprecated Enumerable.sum in favor of Ruby's native implementation available since 2.4. Sum of non-numeric elements requires an initial argument. (called from visit_collection at /home/travis/build/FutureProofRetail/business-server/vendor/bundle/ruby/3.1.0/gems/mobility-ransack-1.1.0/lib/mobility/ransack.rb:15)
```

Issue seems to be [here](https://github.com/shioyama/mobility-ransack/blob/master/lib/mobility/ransack.rb#L15); to fix, you'll need to pass add an argument into sum; I'd put in a PR but I'm not sure what that arg should be.

### PR DESCRIPTION
**Pull request by mhenrixon**
This should close #21 but I am not sure whether or not it is still compatible with previous rails versions.

### CODE REVIEW

**Comment by shioyama** [comment]
Thank you for the PR! ❤️ Just running CI now, I'll have a closer look on the weekend.

**Comment by shioyama** [comment]
> I am not sure whether or not it is still compatible with previous rails versions.

CI says it is compatible with 5.2 and 6.0, and 6.1. I need to update to run against 7.0 as well.

**Comment by mhenrixon** [comment]
I updated CI to test against rails 7.0 and ruby 3.0 and 3.1 (since we are using that). Give it another approval and I'll address anything that comes up in this PR.

**Comment by mhenrixon** [comment]
@shioyama could you approve the CI run?

**Comment by shioyama** [comment]
I've been very busy the past couple months but I'll have a look at this on the weekend.

**Pull request merged**
