### PR TITLE
Add search of accosiation translated fields

### LINKED ISSUE #18: Searching for objects in belongs_to associations
Isn't that possible or am I missing something? For instance:

```
class Athlete < ApplicationRecord
	belongs_to :playing_position
end

class PlayingPosition < ApplicationRecord
	extend Mobility
	
	translates :name
end
```

pry(main)> Athlete.ransack(playing_position_name_cont: 'pont').result.size
   (0.7ms)  SELECT COUNT(*) FROM `athletes` LEFT OUTER JOIN `playing_positions` ON `playing_positions`.`id` = `athletes`.`playing_position_id` WHERE `PlayingPosition_name_pt_br_string_translations`.`value` LIKE '%pont%'
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'PlayingPosition_name_pt_br_string_translations.value' in 'where clause'
from /Users/fabiano/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
Caused by Mysql2::Error: Unknown column 'PlayingPosition_name_pt_br_string_translations.value' in 'where clause'
from /Users/fabiano/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'

### PR DESCRIPTION
**Pull request by jalkoby**
Fixes #18

### CODE REVIEW

**Comment by shioyama** [comment]
Thanks very much for the PR! Sorry hadn't noticed #18. I'll have a look at this soon and review.

**Comment by shioyama** [comment]
Do you think you could split out the specs (and added table/model) as a separate commit? I'd like to merge that first as a pending spec so the problem is well-defined.

**Comment by jalkoby** [comment]
@shioyama done

**Comment by shioyama** [comment]
Thanks! I made some minor changes and cherry-picked to master in b8f3b9944ccadca528cd1b2cd10e07cf967c251d

**Comment by shioyama** [comment]
This makes the problem clear now, which is great. I just need to look through your other commit carefully. My hope is that maybe it can be simplified a bit, but that may be overly optimistic :sweat_smile:

**Comment by shioyama** [comment]
I'm going to close this in favour of #20, but thanks very much for pointing in the right direction!

**Pull request closed without merging**
